# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Core_2.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1570, 731)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.video_plate = QtWidgets.QLabel(self.centralwidget)
        self.video_plate.setGeometry(QtCore.QRect(270, 60, 1031, 541))
        self.video_plate.setStyleSheet("border-width: 1px;\n"
"background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-color: rgb(0, 0, 0)")
        self.video_plate.setText("")
        self.video_plate.setObjectName("video_plate")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 91, 51))
        palette = QtGui.QPalette()
        self.label_2.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("font-weight:bold\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 230, 81, 17))
        self.label_3.setStyleSheet("font-weight:bold")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 110, 91, 17))
        self.label_4.setStyleSheet("font-weight:bold")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(50, 250, 121, 161))
        self.label_5.setStyleSheet("border-width: 2px;\n"
"border-color: rgb(116, 116, 116);\n"
"border-style: solid;")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.target_detect = QtWidgets.QCheckBox(self.centralwidget)
        self.target_detect.setGeometry(QtCore.QRect(60, 260, 99, 22))
        self.target_detect.setObjectName("target_detect")
        self.traffic_light_detect = QtWidgets.QCheckBox(self.centralwidget)
        self.traffic_light_detect.setGeometry(QtCore.QRect(60, 290, 99, 22))
        self.traffic_light_detect.setObjectName("traffic_light_detect")
        self.cars_detect = QtWidgets.QCheckBox(self.centralwidget)
        self.cars_detect.setGeometry(QtCore.QRect(60, 320, 99, 22))
        self.cars_detect.setObjectName("cars_detect")
        self.people_detect = QtWidgets.QCheckBox(self.centralwidget)
        self.people_detect.setGeometry(QtCore.QRect(60, 350, 99, 22))
        self.people_detect.setObjectName("people_detect")
        self.openFIleButton = QtWidgets.QPushButton(self.centralwidget)
        self.openFIleButton.setGeometry(QtCore.QRect(50, 170, 97, 26))
        self.openFIleButton.setStyleSheet("fo\n"
"font: 12pt \"Abyssinica SIL\";\n"
"color: rgb(0, 85, 0);")
        self.openFIleButton.setObjectName("openFIleButton")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(1340, 290, 91, 17))
        self.label_6.setStyleSheet("font-weight:bold")
        self.label_6.setObjectName("label_6")
        self.red_light = QtWidgets.QFrame(self.centralwidget)
        self.red_light.setGeometry(QtCore.QRect(1360, 320, 61, 31))
        self.red_light.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.red_light.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.red_light.setFrameShadow(QtWidgets.QFrame.Raised)
        self.red_light.setObjectName("red_light")
        self.red_light.setVisible(False)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(1340, 450, 91, 17))
        self.label_7.setStyleSheet("font-weight:bold")
        self.label_7.setObjectName("label_7")
        self.license_graph = QtWidgets.QLabel(self.centralwidget)
        self.license_graph.setGeometry(QtCore.QRect(1360, 480, 141, 31))
        self.license_graph.setStyleSheet("border-width: 2px;\n"
"background-color: rgb(255, 255, 255);\n"
"border-color: rgb(116, 116, 116);\n"
"border-style: solid;")
        self.license_graph.setText("")
        self.license_graph.setObjectName("license_graph")
        self.aboutLabel = QtWidgets.QLabel(self.centralwidget)
        self.aboutLabel.setGeometry(QtCore.QRect(470, 620, 631, 61))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.aboutLabel.setFont(font)
        self.aboutLabel.setStyleSheet("color: rgb(85, 0, 0);")
        self.aboutLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.aboutLabel.setObjectName("aboutLabel")
        self.license_plate_detect = QtWidgets.QCheckBox(self.centralwidget)
        self.license_plate_detect.setGeometry(QtCore.QRect(60, 380, 99, 22))
        self.license_plate_detect.setObjectName("license_plate_detect")
        self.green_light = QtWidgets.QFrame(self.centralwidget)
        self.green_light.setGeometry(QtCore.QRect(1430, 320, 61, 31))
        self.green_light.setStyleSheet("background-color: rgb(0,255, 0);")
        self.green_light.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.green_light.setFrameShadow(QtWidgets.QFrame.Raised)
        self.green_light.setObjectName("green_light")
        self.green_light.setVisible(False)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(10, 410, 91, 51))
        palette = QtGui.QPalette()
        self.label_9.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("font-weight:bold\n"
"")
        self.label_9.setObjectName("label_9")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(20, 450, 231, 251))
        self.textEdit.setObjectName("textEdit")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(1340, 80, 91, 17))
        self.label_11.setStyleSheet("font-weight:bold")
        self.label_11.setObjectName("label_11")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(1365, 150, 171, 121))
        self.tableWidget.setAutoScrollMargin(11)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 60, 20, 361))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(250, 60, 20, 361))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(20, 400, 241, 41))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(20, 50, 241, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.closeFileButton = QtWidgets.QPushButton(self.centralwidget)
        self.closeFileButton.setGeometry(QtCore.QRect(50, 200, 97, 26))
        self.closeFileButton.setStyleSheet("fo\n"
"font: 12pt \"Abyssinica SIL\";\n"
"color: rgb(0, 85, 0);")
        self.closeFileButton.setObjectName("closeFileButton")
        self.license_result = QtWidgets.QLabel(self.centralwidget)
        self.license_result.setGeometry(QtCore.QRect(1360, 530, 141, 31))
        self.license_result.setStyleSheet("border-width: 2px;\n"
"background-color: rgb(255, 255, 255);\n"
"border-color: rgb(116, 116, 116);\n"
"border-style: solid;")
        self.license_result.setText("")
        self.license_result.setObjectName("license_result")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(1340, 380, 151, 17))
        self.label_12.setStyleSheet("font-weight:bold")
        self.label_12.setObjectName("label_12")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(1310, 60, 20, 551))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(1320, 600, 231, 20))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.break_traffic_warning = QtWidgets.QFrame(self.centralwidget)
        self.break_traffic_warning.setGeometry(QtCore.QRect(1360, 410, 51, 21))
        self.break_traffic_warning.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.break_traffic_warning.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.break_traffic_warning.setFrameShadow(QtWidgets.QFrame.Raised)
        self.break_traffic_warning.setObjectName("break_traffic_warning")
        self.break_traffic_label = QtWidgets.QLabel(self.centralwidget)
        self.break_traffic_label.setGeometry(QtCore.QRect(1430, 410, 91, 17))
        self.break_traffic_label.setStyleSheet("font-weight:bold")
        self.break_traffic_label.setObjectName("break_traffic_label")
        self.break_traffic_label.setVisible(False)
        self.break_traffic_warning.setVisible(False)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(50, 140, 181, 24))
        self.lineEdit.setObjectName("lineEdit")
        self.lookVisualDataButton = QtWidgets.QPushButton(self.centralwidget)
        self.lookVisualDataButton.setGeometry(QtCore.QRect(1360, 110, 131, 26))
        self.lookVisualDataButton.setObjectName("lookVisualDataButton")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(30, 60, 91, 17))
        self.label_8.setStyleSheet("font-weight:bold")
        self.label_8.setObjectName("label_8")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(30, 80, 101, 24))
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(130, 80, 61, 24))
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(200, 80, 51, 26))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1570, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "系统设置"))
        self.label_3.setText(_translate("MainWindow", "功能开关"))
        self.label_4.setText(_translate("MainWindow", "载入监控视频"))
        self.target_detect.setText(_translate("MainWindow", "目标识别"))
        self.traffic_light_detect.setText(_translate("MainWindow", "红绿灯检测"))
        self.cars_detect.setText(_translate("MainWindow", "车流检测"))
        self.people_detect.setText(_translate("MainWindow", "人流检测"))
        self.openFIleButton.setText(_translate("MainWindow", "刷新视频流"))
        self.label_6.setText(_translate("MainWindow", "红绿灯状态"))
        self.label_7.setText(_translate("MainWindow", "车牌识别结果"))
        self.aboutLabel.setText(_translate("MainWindow", "交通路口智能监控系统"))
        self.license_plate_detect.setText(_translate("MainWindow", "车牌识别"))
        self.label_9.setText(_translate("MainWindow", " 系统日志"))
        self.label_11.setText(_translate("MainWindow", "统计数据"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "people"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "car"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "motor"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "数量"))
        self.closeFileButton.setText(_translate("MainWindow", "关闭视频流"))
        self.label_12.setText(_translate("MainWindow", "行人闯红灯警报"))
        self.break_traffic_label.setText(_translate("MainWindow", "闯红灯"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "rtmp流"))
        self.lookVisualDataButton.setText(_translate("MainWindow", "查看可视化数据"))
        self.label_8.setText(_translate("MainWindow", "连接服务器"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "IP"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "Port"))
        self.pushButton.setText(_translate("MainWindow", "connect"))
