# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'simple.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1361, 731)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.video_plate = QtWidgets.QLabel(self.centralwidget)
        self.video_plate.setGeometry(QtCore.QRect(270, 60, 1031, 541))
        self.video_plate.setStyleSheet("border-width: 1px;\n"
"background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-color: rgb(0, 0, 0)")
        self.video_plate.setText("")
        self.video_plate.setObjectName("video_plate")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 91, 51))
        palette = QtGui.QPalette()
        self.label_2.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("font-weight:bold\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 230, 81, 17))
        self.label_3.setStyleSheet("font-weight:bold")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 110, 91, 17))
        self.label_4.setStyleSheet("font-weight:bold")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(50, 250, 121, 161))
        self.label_5.setStyleSheet("border-width: 2px;\n"
"border-color: rgb(116, 116, 116);\n"
"border-style: solid;")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.target_detect = QtWidgets.QCheckBox(self.centralwidget)
        self.target_detect.setGeometry(QtCore.QRect(60, 260, 99, 22))
        self.target_detect.setObjectName("target_detect")
        self.traffic_light_detect = QtWidgets.QCheckBox(self.centralwidget)
        self.traffic_light_detect.setGeometry(QtCore.QRect(60, 290, 99, 22))
        self.traffic_light_detect.setObjectName("traffic_light_detect")
        self.cars_detect = QtWidgets.QCheckBox(self.centralwidget)
        self.cars_detect.setGeometry(QtCore.QRect(60, 320, 99, 22))
        self.cars_detect.setObjectName("cars_detect")
        self.people_detect = QtWidgets.QCheckBox(self.centralwidget)
        self.people_detect.setGeometry(QtCore.QRect(60, 350, 99, 22))
        self.people_detect.setObjectName("people_detect")
        self.openFIleButton = QtWidgets.QPushButton(self.centralwidget)
        self.openFIleButton.setGeometry(QtCore.QRect(50, 170, 97, 26))
        self.openFIleButton.setStyleSheet("fo\n"
"font: 12pt \"Abyssinica SIL\";\n"
"color: rgb(0, 85, 0);")
        self.openFIleButton.setObjectName("openFIleButton")
        self.aboutLabel = QtWidgets.QLabel(self.centralwidget)
        self.aboutLabel.setGeometry(QtCore.QRect(470, 620, 631, 61))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.aboutLabel.setFont(font)
        self.aboutLabel.setStyleSheet("color: rgb(85, 0, 0);")
        self.aboutLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.aboutLabel.setObjectName("aboutLabel")
        self.license_plate_detect = QtWidgets.QCheckBox(self.centralwidget)
        self.license_plate_detect.setGeometry(QtCore.QRect(60, 380, 99, 22))
        self.license_plate_detect.setObjectName("license_plate_detect")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(10, 410, 91, 51))
        palette = QtGui.QPalette()
        self.label_9.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("font-weight:bold\n"
"")
        self.label_9.setObjectName("label_9")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(20, 450, 231, 251))
        self.textEdit.setObjectName("textEdit")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 60, 20, 361))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(250, 60, 20, 361))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(20, 400, 241, 41))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(20, 50, 241, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.closeFileButton = QtWidgets.QPushButton(self.centralwidget)
        self.closeFileButton.setGeometry(QtCore.QRect(50, 200, 97, 26))
        self.closeFileButton.setStyleSheet("fo\n"
"font: 12pt \"Abyssinica SIL\";\n"
"color: rgb(0, 85, 0);")
        self.closeFileButton.setObjectName("closeFileButton")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(50, 140, 181, 24))
        self.lineEdit.setObjectName("lineEdit")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(30, 60, 91, 17))
        self.label_8.setStyleSheet("font-weight:bold")
        self.label_8.setObjectName("label_8")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(30, 80, 101, 24))
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(130, 80, 61, 24))
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(200, 80, 61, 26))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1361, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "系统设置"))
        self.label_3.setText(_translate("MainWindow", "功能开关"))
        self.label_4.setText(_translate("MainWindow", "载入监控视频"))
        self.target_detect.setText(_translate("MainWindow", "xxx"))
        self.traffic_light_detect.setText(_translate("MainWindow", "xxx"))
        self.cars_detect.setText(_translate("MainWindow", "xxx"))
        self.people_detect.setText(_translate("MainWindow", "xxx"))
        self.openFIleButton.setText(_translate("MainWindow", "刷新视频流"))
        self.aboutLabel.setText(_translate("MainWindow", "智能监控系统"))
        self.license_plate_detect.setText(_translate("MainWindow", "xxx"))
        self.label_9.setText(_translate("MainWindow", " 系统日志"))
        self.closeFileButton.setText(_translate("MainWindow", "关闭视频流"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "rtmp流"))
        self.label_8.setText(_translate("MainWindow", "连接服务器"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "IP"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "Port"))
        self.pushButton.setText(_translate("MainWindow", "connect"))
